/**
 * generated by Xtext 2.15.0
 */
package org.xtext.example.mydsl.pascal;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>constant</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.pascal.constant#getUnsignedNumber <em>Unsigned Number</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.pascal.constant#getSign1 <em>Sign1</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.pascal.constant#getIdentifier1 <em>Identifier1</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.pascal.constant#getSign2 <em>Sign2</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.pascal.constant#getIdentifier2 <em>Identifier2</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.pascal.constant#getString <em>String</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.pascal.constant#getConstantChr <em>Constant Chr</em>}</li>
 * </ul>
 * </p>
 *
 * @see org.xtext.example.mydsl.pascal.PascalPackage#getconstant()
 * @model
 * @generated
 */
public interface constant extends EObject
{
  /**
   * Returns the value of the '<em><b>Unsigned Number</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Unsigned Number</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Unsigned Number</em>' containment reference.
   * @see #setUnsignedNumber(unsignedNumber)
   * @see org.xtext.example.mydsl.pascal.PascalPackage#getconstant_UnsignedNumber()
   * @model containment="true"
   * @generated
   */
  unsignedNumber getUnsignedNumber();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.pascal.constant#getUnsignedNumber <em>Unsigned Number</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Unsigned Number</em>' containment reference.
   * @see #getUnsignedNumber()
   * @generated
   */
  void setUnsignedNumber(unsignedNumber value);

  /**
   * Returns the value of the '<em><b>Sign1</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Sign1</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Sign1</em>' containment reference.
   * @see #setSign1(sign)
   * @see org.xtext.example.mydsl.pascal.PascalPackage#getconstant_Sign1()
   * @model containment="true"
   * @generated
   */
  sign getSign1();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.pascal.constant#getSign1 <em>Sign1</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Sign1</em>' containment reference.
   * @see #getSign1()
   * @generated
   */
  void setSign1(sign value);

  /**
   * Returns the value of the '<em><b>Identifier1</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Identifier1</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Identifier1</em>' containment reference.
   * @see #setIdentifier1(identifier)
   * @see org.xtext.example.mydsl.pascal.PascalPackage#getconstant_Identifier1()
   * @model containment="true"
   * @generated
   */
  identifier getIdentifier1();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.pascal.constant#getIdentifier1 <em>Identifier1</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Identifier1</em>' containment reference.
   * @see #getIdentifier1()
   * @generated
   */
  void setIdentifier1(identifier value);

  /**
   * Returns the value of the '<em><b>Sign2</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Sign2</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Sign2</em>' containment reference.
   * @see #setSign2(sign)
   * @see org.xtext.example.mydsl.pascal.PascalPackage#getconstant_Sign2()
   * @model containment="true"
   * @generated
   */
  sign getSign2();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.pascal.constant#getSign2 <em>Sign2</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Sign2</em>' containment reference.
   * @see #getSign2()
   * @generated
   */
  void setSign2(sign value);

  /**
   * Returns the value of the '<em><b>Identifier2</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Identifier2</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Identifier2</em>' containment reference.
   * @see #setIdentifier2(identifier)
   * @see org.xtext.example.mydsl.pascal.PascalPackage#getconstant_Identifier2()
   * @model containment="true"
   * @generated
   */
  identifier getIdentifier2();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.pascal.constant#getIdentifier2 <em>Identifier2</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Identifier2</em>' containment reference.
   * @see #getIdentifier2()
   * @generated
   */
  void setIdentifier2(identifier value);

  /**
   * Returns the value of the '<em><b>String</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>String</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>String</em>' containment reference.
   * @see #setString(StringStart)
   * @see org.xtext.example.mydsl.pascal.PascalPackage#getconstant_String()
   * @model containment="true"
   * @generated
   */
  StringStart getString();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.pascal.constant#getString <em>String</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>String</em>' containment reference.
   * @see #getString()
   * @generated
   */
  void setString(StringStart value);

  /**
   * Returns the value of the '<em><b>Constant Chr</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Constant Chr</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Constant Chr</em>' containment reference.
   * @see #setConstantChr(constantChr)
   * @see org.xtext.example.mydsl.pascal.PascalPackage#getconstant_ConstantChr()
   * @model containment="true"
   * @generated
   */
  constantChr getConstantChr();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.pascal.constant#getConstantChr <em>Constant Chr</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Constant Chr</em>' containment reference.
   * @see #getConstantChr()
   * @generated
   */
  void setConstantChr(constantChr value);

} // constant
