/**
 * generated by Xtext 2.15.0
 */
package org.xtext.example.mydsl.pascal;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>field List</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.pascal.fieldList#getFixedPart <em>Fixed Part</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.pascal.fieldList#getSemiTerminal <em>Semi Terminal</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.pascal.fieldList#getVariantPart1 <em>Variant Part1</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.pascal.fieldList#getVariantPart2 <em>Variant Part2</em>}</li>
 * </ul>
 * </p>
 *
 * @see org.xtext.example.mydsl.pascal.PascalPackage#getfieldList()
 * @model
 * @generated
 */
public interface fieldList extends EObject
{
  /**
   * Returns the value of the '<em><b>Fixed Part</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Fixed Part</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Fixed Part</em>' containment reference.
   * @see #setFixedPart(fixedPart)
   * @see org.xtext.example.mydsl.pascal.PascalPackage#getfieldList_FixedPart()
   * @model containment="true"
   * @generated
   */
  fixedPart getFixedPart();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.pascal.fieldList#getFixedPart <em>Fixed Part</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Fixed Part</em>' containment reference.
   * @see #getFixedPart()
   * @generated
   */
  void setFixedPart(fixedPart value);

  /**
   * Returns the value of the '<em><b>Semi Terminal</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Semi Terminal</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Semi Terminal</em>' attribute.
   * @see #setSemiTerminal(String)
   * @see org.xtext.example.mydsl.pascal.PascalPackage#getfieldList_SemiTerminal()
   * @model
   * @generated
   */
  String getSemiTerminal();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.pascal.fieldList#getSemiTerminal <em>Semi Terminal</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Semi Terminal</em>' attribute.
   * @see #getSemiTerminal()
   * @generated
   */
  void setSemiTerminal(String value);

  /**
   * Returns the value of the '<em><b>Variant Part1</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Variant Part1</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Variant Part1</em>' containment reference.
   * @see #setVariantPart1(variantPart)
   * @see org.xtext.example.mydsl.pascal.PascalPackage#getfieldList_VariantPart1()
   * @model containment="true"
   * @generated
   */
  variantPart getVariantPart1();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.pascal.fieldList#getVariantPart1 <em>Variant Part1</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Variant Part1</em>' containment reference.
   * @see #getVariantPart1()
   * @generated
   */
  void setVariantPart1(variantPart value);

  /**
   * Returns the value of the '<em><b>Variant Part2</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Variant Part2</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Variant Part2</em>' containment reference.
   * @see #setVariantPart2(variantPart)
   * @see org.xtext.example.mydsl.pascal.PascalPackage#getfieldList_VariantPart2()
   * @model containment="true"
   * @generated
   */
  variantPart getVariantPart2();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.pascal.fieldList#getVariantPart2 <em>Variant Part2</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Variant Part2</em>' containment reference.
   * @see #getVariantPart2()
   * @generated
   */
  void setVariantPart2(variantPart value);

} // fieldList
