/**
 * generated by Xtext 2.15.0
 */
package org.xtext.example.mydsl.pascal;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>goto Statement</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.pascal.gotoStatement#getLabelStart <em>Label Start</em>}</li>
 * </ul>
 * </p>
 *
 * @see org.xtext.example.mydsl.pascal.PascalPackage#getgotoStatement()
 * @model
 * @generated
 */
public interface gotoStatement extends EObject
{
  /**
   * Returns the value of the '<em><b>Label Start</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Label Start</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Label Start</em>' containment reference.
   * @see #setLabelStart(labelStart)
   * @see org.xtext.example.mydsl.pascal.PascalPackage#getgotoStatement_LabelStart()
   * @model containment="true"
   * @generated
   */
  labelStart getLabelStart();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.pascal.gotoStatement#getLabelStart <em>Label Start</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Label Start</em>' containment reference.
   * @see #getLabelStart()
   * @generated
   */
  void setLabelStart(labelStart value);

} // gotoStatement
