/**
 * generated by Xtext 2.15.0
 */
package org.xtext.example.mydsl.pascal;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>label Declaration Part</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.pascal.labelDeclarationPart#getLabelStart1 <em>Label Start1</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.pascal.labelDeclarationPart#getCommaTerminal <em>Comma Terminal</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.pascal.labelDeclarationPart#getLabelStart2 <em>Label Start2</em>}</li>
 * </ul>
 * </p>
 *
 * @see org.xtext.example.mydsl.pascal.PascalPackage#getlabelDeclarationPart()
 * @model
 * @generated
 */
public interface labelDeclarationPart extends EObject
{
  /**
   * Returns the value of the '<em><b>Label Start1</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Label Start1</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Label Start1</em>' containment reference.
   * @see #setLabelStart1(labelStart)
   * @see org.xtext.example.mydsl.pascal.PascalPackage#getlabelDeclarationPart_LabelStart1()
   * @model containment="true"
   * @generated
   */
  labelStart getLabelStart1();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.pascal.labelDeclarationPart#getLabelStart1 <em>Label Start1</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Label Start1</em>' containment reference.
   * @see #getLabelStart1()
   * @generated
   */
  void setLabelStart1(labelStart value);

  /**
   * Returns the value of the '<em><b>Comma Terminal</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Comma Terminal</em>' attribute list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Comma Terminal</em>' attribute list.
   * @see org.xtext.example.mydsl.pascal.PascalPackage#getlabelDeclarationPart_CommaTerminal()
   * @model unique="false"
   * @generated
   */
  EList<String> getCommaTerminal();

  /**
   * Returns the value of the '<em><b>Label Start2</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.mydsl.pascal.labelStart}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Label Start2</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Label Start2</em>' containment reference list.
   * @see org.xtext.example.mydsl.pascal.PascalPackage#getlabelDeclarationPart_LabelStart2()
   * @model containment="true"
   * @generated
   */
  EList<labelStart> getLabelStart2();

} // labelDeclarationPart
