/**
 * generated by Xtext 2.15.0
 */
package org.xtext.example.mydsl.pascal;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>program Heading</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.pascal.programHeading#getIdentifier1 <em>Identifier1</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.pascal.programHeading#getIdentifierList <em>Identifier List</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.pascal.programHeading#getIdentifier2 <em>Identifier2</em>}</li>
 * </ul>
 * </p>
 *
 * @see org.xtext.example.mydsl.pascal.PascalPackage#getprogramHeading()
 * @model
 * @generated
 */
public interface programHeading extends EObject
{
  /**
   * Returns the value of the '<em><b>Identifier1</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Identifier1</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Identifier1</em>' containment reference.
   * @see #setIdentifier1(identifier)
   * @see org.xtext.example.mydsl.pascal.PascalPackage#getprogramHeading_Identifier1()
   * @model containment="true"
   * @generated
   */
  identifier getIdentifier1();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.pascal.programHeading#getIdentifier1 <em>Identifier1</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Identifier1</em>' containment reference.
   * @see #getIdentifier1()
   * @generated
   */
  void setIdentifier1(identifier value);

  /**
   * Returns the value of the '<em><b>Identifier List</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.mydsl.pascal.identifierList}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Identifier List</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Identifier List</em>' containment reference list.
   * @see org.xtext.example.mydsl.pascal.PascalPackage#getprogramHeading_IdentifierList()
   * @model containment="true"
   * @generated
   */
  EList<identifierList> getIdentifierList();

  /**
   * Returns the value of the '<em><b>Identifier2</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Identifier2</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Identifier2</em>' containment reference.
   * @see #setIdentifier2(identifier)
   * @see org.xtext.example.mydsl.pascal.PascalPackage#getprogramHeading_Identifier2()
   * @model containment="true"
   * @generated
   */
  identifier getIdentifier2();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.pascal.programHeading#getIdentifier2 <em>Identifier2</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Identifier2</em>' containment reference.
   * @see #getIdentifier2()
   * @generated
   */
  void setIdentifier2(identifier value);

} // programHeading
