/**
 * generated by Xtext 2.15.0
 */
package org.xtext.example.mydsl.pascal;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>record Section</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.pascal.recordSection#getSemiTerminal <em>Semi Terminal</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.pascal.recordSection#getRecordSection <em>Record Section</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.pascal.recordSection#getIdentifierList <em>Identifier List</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.pascal.recordSection#getTypeStart <em>Type Start</em>}</li>
 * </ul>
 * </p>
 *
 * @see org.xtext.example.mydsl.pascal.PascalPackage#getrecordSection()
 * @model
 * @generated
 */
public interface recordSection extends fixedPart
{
  /**
   * Returns the value of the '<em><b>Semi Terminal</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Semi Terminal</em>' attribute list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Semi Terminal</em>' attribute list.
   * @see org.xtext.example.mydsl.pascal.PascalPackage#getrecordSection_SemiTerminal()
   * @model unique="false"
   * @generated
   */
  EList<String> getSemiTerminal();

  /**
   * Returns the value of the '<em><b>Record Section</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.mydsl.pascal.recordSection}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Record Section</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Record Section</em>' containment reference list.
   * @see org.xtext.example.mydsl.pascal.PascalPackage#getrecordSection_RecordSection()
   * @model containment="true"
   * @generated
   */
  EList<recordSection> getRecordSection();

  /**
   * Returns the value of the '<em><b>Identifier List</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Identifier List</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Identifier List</em>' containment reference.
   * @see #setIdentifierList(identifierList)
   * @see org.xtext.example.mydsl.pascal.PascalPackage#getrecordSection_IdentifierList()
   * @model containment="true"
   * @generated
   */
  identifierList getIdentifierList();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.pascal.recordSection#getIdentifierList <em>Identifier List</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Identifier List</em>' containment reference.
   * @see #getIdentifierList()
   * @generated
   */
  void setIdentifierList(identifierList value);

  /**
   * Returns the value of the '<em><b>Type Start</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Type Start</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type Start</em>' containment reference.
   * @see #setTypeStart(typeStart)
   * @see org.xtext.example.mydsl.pascal.PascalPackage#getrecordSection_TypeStart()
   * @model containment="true"
   * @generated
   */
  typeStart getTypeStart();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.pascal.recordSection#getTypeStart <em>Type Start</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Type Start</em>' containment reference.
   * @see #getTypeStart()
   * @generated
   */
  void setTypeStart(typeStart value);

} // recordSection
