/**
 * generated by Xtext 2.15.0
 */
package org.xtext.example.mydsl.pascal;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>stringtype</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.pascal.stringtype#getStringTerminal <em>String Terminal</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.pascal.stringtype#getID <em>ID</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.pascal.stringtype#getUnsignedNumber <em>Unsigned Number</em>}</li>
 * </ul>
 * </p>
 *
 * @see org.xtext.example.mydsl.pascal.PascalPackage#getstringtype()
 * @model
 * @generated
 */
public interface stringtype extends EObject
{
  /**
   * Returns the value of the '<em><b>String Terminal</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>String Terminal</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>String Terminal</em>' attribute.
   * @see #setStringTerminal(String)
   * @see org.xtext.example.mydsl.pascal.PascalPackage#getstringtype_StringTerminal()
   * @model
   * @generated
   */
  String getStringTerminal();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.pascal.stringtype#getStringTerminal <em>String Terminal</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>String Terminal</em>' attribute.
   * @see #getStringTerminal()
   * @generated
   */
  void setStringTerminal(String value);

  /**
   * Returns the value of the '<em><b>ID</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>ID</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>ID</em>' containment reference.
   * @see #setID(identifier)
   * @see org.xtext.example.mydsl.pascal.PascalPackage#getstringtype_ID()
   * @model containment="true"
   * @generated
   */
  identifier getID();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.pascal.stringtype#getID <em>ID</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>ID</em>' containment reference.
   * @see #getID()
   * @generated
   */
  void setID(identifier value);

  /**
   * Returns the value of the '<em><b>Unsigned Number</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Unsigned Number</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Unsigned Number</em>' containment reference.
   * @see #setUnsignedNumber(unsignedNumber)
   * @see org.xtext.example.mydsl.pascal.PascalPackage#getstringtype_UnsignedNumber()
   * @model containment="true"
   * @generated
   */
  unsignedNumber getUnsignedNumber();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.pascal.stringtype#getUnsignedNumber <em>Unsigned Number</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Unsigned Number</em>' containment reference.
   * @see #getUnsignedNumber()
   * @generated
   */
  void setUnsignedNumber(unsignedNumber value);

} // stringtype
