/**
 * generated by Xtext 2.15.0
 */
package org.xtext.example.mydsl.pascal;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>structured Type</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.pascal.structuredType#getUnpackedStructuredType1 <em>Unpacked Structured Type1</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.pascal.structuredType#getUnpackedStructuredType2 <em>Unpacked Structured Type2</em>}</li>
 * </ul>
 * </p>
 *
 * @see org.xtext.example.mydsl.pascal.PascalPackage#getstructuredType()
 * @model
 * @generated
 */
public interface structuredType extends EObject
{
  /**
   * Returns the value of the '<em><b>Unpacked Structured Type1</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Unpacked Structured Type1</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Unpacked Structured Type1</em>' containment reference.
   * @see #setUnpackedStructuredType1(unpackedStructuredType)
   * @see org.xtext.example.mydsl.pascal.PascalPackage#getstructuredType_UnpackedStructuredType1()
   * @model containment="true"
   * @generated
   */
  unpackedStructuredType getUnpackedStructuredType1();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.pascal.structuredType#getUnpackedStructuredType1 <em>Unpacked Structured Type1</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Unpacked Structured Type1</em>' containment reference.
   * @see #getUnpackedStructuredType1()
   * @generated
   */
  void setUnpackedStructuredType1(unpackedStructuredType value);

  /**
   * Returns the value of the '<em><b>Unpacked Structured Type2</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Unpacked Structured Type2</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Unpacked Structured Type2</em>' containment reference.
   * @see #setUnpackedStructuredType2(unpackedStructuredType)
   * @see org.xtext.example.mydsl.pascal.PascalPackage#getstructuredType_UnpackedStructuredType2()
   * @model containment="true"
   * @generated
   */
  unpackedStructuredType getUnpackedStructuredType2();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.pascal.structuredType#getUnpackedStructuredType2 <em>Unpacked Structured Type2</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Unpacked Structured Type2</em>' containment reference.
   * @see #getUnpackedStructuredType2()
   * @generated
   */
  void setUnpackedStructuredType2(unpackedStructuredType value);

} // structuredType
