/**
 * generated by Xtext 2.15.0
 */
package org.xtext.example.mydsl.pascal;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>unsigned Real</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.pascal.unsignedReal#getUnsignedReal <em>Unsigned Real</em>}</li>
 * </ul>
 * </p>
 *
 * @see org.xtext.example.mydsl.pascal.PascalPackage#getunsignedReal()
 * @model
 * @generated
 */
public interface unsignedReal extends EObject
{
  /**
   * Returns the value of the '<em><b>Unsigned Real</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Unsigned Real</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Unsigned Real</em>' attribute.
   * @see #setUnsignedReal(String)
   * @see org.xtext.example.mydsl.pascal.PascalPackage#getunsignedReal_UnsignedReal()
   * @model
   * @generated
   */
  String getUnsignedReal();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.pascal.unsignedReal#getUnsignedReal <em>Unsigned Real</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Unsigned Real</em>' attribute.
   * @see #getUnsignedReal()
   * @generated
   */
  void setUnsignedReal(String value);

} // unsignedReal
