/**
 * generated by Xtext 2.15.0
 */
package org.xtext.example.mydsl.pascal;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>variable Declaration Part</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.pascal.variableDeclarationPart#getVariableDeclaration1 <em>Variable Declaration1</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.pascal.variableDeclarationPart#getSemiTerminal <em>Semi Terminal</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.pascal.variableDeclarationPart#getVariableDeclaration2 <em>Variable Declaration2</em>}</li>
 * </ul>
 * </p>
 *
 * @see org.xtext.example.mydsl.pascal.PascalPackage#getvariableDeclarationPart()
 * @model
 * @generated
 */
public interface variableDeclarationPart extends EObject
{
  /**
   * Returns the value of the '<em><b>Variable Declaration1</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Variable Declaration1</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Variable Declaration1</em>' containment reference.
   * @see #setVariableDeclaration1(variableDeclaration)
   * @see org.xtext.example.mydsl.pascal.PascalPackage#getvariableDeclarationPart_VariableDeclaration1()
   * @model containment="true"
   * @generated
   */
  variableDeclaration getVariableDeclaration1();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.pascal.variableDeclarationPart#getVariableDeclaration1 <em>Variable Declaration1</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Variable Declaration1</em>' containment reference.
   * @see #getVariableDeclaration1()
   * @generated
   */
  void setVariableDeclaration1(variableDeclaration value);

  /**
   * Returns the value of the '<em><b>Semi Terminal</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Semi Terminal</em>' attribute list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Semi Terminal</em>' attribute list.
   * @see org.xtext.example.mydsl.pascal.PascalPackage#getvariableDeclarationPart_SemiTerminal()
   * @model unique="false"
   * @generated
   */
  EList<String> getSemiTerminal();

  /**
   * Returns the value of the '<em><b>Variable Declaration2</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.mydsl.pascal.variableDeclaration}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Variable Declaration2</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Variable Declaration2</em>' containment reference list.
   * @see org.xtext.example.mydsl.pascal.PascalPackage#getvariableDeclarationPart_VariableDeclaration2()
   * @model containment="true"
   * @generated
   */
  EList<variableDeclaration> getVariableDeclaration2();

} // variableDeclarationPart
