/**
 * generated by Xtext 2.16.0-SNAPSHOT
 */
package org.xtext.example.mydsl.pascal;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>factor</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.pascal.factor#getVariable <em>Variable</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.pascal.factor#getExpression <em>Expression</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.pascal.factor#getFunctionDesignator <em>Function Designator</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.pascal.factor#getUnsignedConstant <em>Unsigned Constant</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.pascal.factor#getNot <em>Not</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.pascal.factor#getFactor <em>Factor</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.pascal.factor#getBool <em>Bool</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.pascal.PascalPackage#getfactor()
 * @model
 * @generated
 */
public interface factor extends EObject
{
  /**
   * Returns the value of the '<em><b>Variable</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Variable</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Variable</em>' containment reference.
   * @see #setVariable(variable)
   * @see org.xtext.example.mydsl.pascal.PascalPackage#getfactor_Variable()
   * @model containment="true"
   * @generated
   */
  variable getVariable();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.pascal.factor#getVariable <em>Variable</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Variable</em>' containment reference.
   * @see #getVariable()
   * @generated
   */
  void setVariable(variable value);

  /**
   * Returns the value of the '<em><b>Expression</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Expression</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Expression</em>' containment reference.
   * @see #setExpression(expression)
   * @see org.xtext.example.mydsl.pascal.PascalPackage#getfactor_Expression()
   * @model containment="true"
   * @generated
   */
  expression getExpression();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.pascal.factor#getExpression <em>Expression</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Expression</em>' containment reference.
   * @see #getExpression()
   * @generated
   */
  void setExpression(expression value);

  /**
   * Returns the value of the '<em><b>Function Designator</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Function Designator</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Function Designator</em>' containment reference.
   * @see #setFunctionDesignator(functionDesignator)
   * @see org.xtext.example.mydsl.pascal.PascalPackage#getfactor_FunctionDesignator()
   * @model containment="true"
   * @generated
   */
  functionDesignator getFunctionDesignator();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.pascal.factor#getFunctionDesignator <em>Function Designator</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Function Designator</em>' containment reference.
   * @see #getFunctionDesignator()
   * @generated
   */
  void setFunctionDesignator(functionDesignator value);

  /**
   * Returns the value of the '<em><b>Unsigned Constant</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Unsigned Constant</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Unsigned Constant</em>' containment reference.
   * @see #setUnsignedConstant(unsignedConstant)
   * @see org.xtext.example.mydsl.pascal.PascalPackage#getfactor_UnsignedConstant()
   * @model containment="true"
   * @generated
   */
  unsignedConstant getUnsignedConstant();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.pascal.factor#getUnsignedConstant <em>Unsigned Constant</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Unsigned Constant</em>' containment reference.
   * @see #getUnsignedConstant()
   * @generated
   */
  void setUnsignedConstant(unsignedConstant value);

  /**
   * Returns the value of the '<em><b>Not</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Not</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Not</em>' attribute.
   * @see #setNot(String)
   * @see org.xtext.example.mydsl.pascal.PascalPackage#getfactor_Not()
   * @model
   * @generated
   */
  String getNot();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.pascal.factor#getNot <em>Not</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Not</em>' attribute.
   * @see #getNot()
   * @generated
   */
  void setNot(String value);

  /**
   * Returns the value of the '<em><b>Factor</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Factor</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Factor</em>' containment reference.
   * @see #setFactor(factor)
   * @see org.xtext.example.mydsl.pascal.PascalPackage#getfactor_Factor()
   * @model containment="true"
   * @generated
   */
  factor getFactor();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.pascal.factor#getFactor <em>Factor</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Factor</em>' containment reference.
   * @see #getFactor()
   * @generated
   */
  void setFactor(factor value);

  /**
   * Returns the value of the '<em><b>Bool</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Bool</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Bool</em>' containment reference.
   * @see #setBool(bool)
   * @see org.xtext.example.mydsl.pascal.PascalPackage#getfactor_Bool()
   * @model containment="true"
   * @generated
   */
  bool getBool();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.pascal.factor#getBool <em>Bool</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Bool</em>' containment reference.
   * @see #getBool()
   * @generated
   */
  void setBool(bool value);

} // factor
