/**
 * generated by Xtext 2.16.0-SNAPSHOT
 */
package org.xtext.example.mydsl.pascal;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>formal Parameter List</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.pascal.formalParameterList#getFormalParameterSection1 <em>Formal Parameter Section1</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.pascal.formalParameterList#getSemiterminal <em>Semiterminal</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.pascal.formalParameterList#getFormalParameterSection2 <em>Formal Parameter Section2</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.pascal.PascalPackage#getformalParameterList()
 * @model
 * @generated
 */
public interface formalParameterList extends EObject
{
  /**
   * Returns the value of the '<em><b>Formal Parameter Section1</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Formal Parameter Section1</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Formal Parameter Section1</em>' containment reference.
   * @see #setFormalParameterSection1(formalParameterSection)
   * @see org.xtext.example.mydsl.pascal.PascalPackage#getformalParameterList_FormalParameterSection1()
   * @model containment="true"
   * @generated
   */
  formalParameterSection getFormalParameterSection1();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.pascal.formalParameterList#getFormalParameterSection1 <em>Formal Parameter Section1</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Formal Parameter Section1</em>' containment reference.
   * @see #getFormalParameterSection1()
   * @generated
   */
  void setFormalParameterSection1(formalParameterSection value);

  /**
   * Returns the value of the '<em><b>Semiterminal</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Semiterminal</em>' attribute list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Semiterminal</em>' attribute list.
   * @see org.xtext.example.mydsl.pascal.PascalPackage#getformalParameterList_Semiterminal()
   * @model unique="false"
   * @generated
   */
  EList<String> getSemiterminal();

  /**
   * Returns the value of the '<em><b>Formal Parameter Section2</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.mydsl.pascal.formalParameterSection}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Formal Parameter Section2</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Formal Parameter Section2</em>' containment reference list.
   * @see org.xtext.example.mydsl.pascal.PascalPackage#getformalParameterList_FormalParameterSection2()
   * @model containment="true"
   * @generated
   */
  EList<formalParameterSection> getFormalParameterSection2();

} // formalParameterList
