/**
 * generated by Xtext 2.16.0-SNAPSHOT
 */
package org.xtext.example.mydsl.pascal;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>record Variable List</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.pascal.recordVariableList#getVariable1 <em>Variable1</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.pascal.recordVariableList#getCommaTerminal <em>Comma Terminal</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.pascal.recordVariableList#getVariable2 <em>Variable2</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.pascal.PascalPackage#getrecordVariableList()
 * @model
 * @generated
 */
public interface recordVariableList extends EObject
{
  /**
   * Returns the value of the '<em><b>Variable1</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Variable1</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Variable1</em>' containment reference.
   * @see #setVariable1(variable)
   * @see org.xtext.example.mydsl.pascal.PascalPackage#getrecordVariableList_Variable1()
   * @model containment="true"
   * @generated
   */
  variable getVariable1();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.pascal.recordVariableList#getVariable1 <em>Variable1</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Variable1</em>' containment reference.
   * @see #getVariable1()
   * @generated
   */
  void setVariable1(variable value);

  /**
   * Returns the value of the '<em><b>Comma Terminal</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Comma Terminal</em>' attribute list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Comma Terminal</em>' attribute list.
   * @see org.xtext.example.mydsl.pascal.PascalPackage#getrecordVariableList_CommaTerminal()
   * @model unique="false"
   * @generated
   */
  EList<String> getCommaTerminal();

  /**
   * Returns the value of the '<em><b>Variable2</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.mydsl.pascal.variable}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Variable2</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Variable2</em>' containment reference list.
   * @see org.xtext.example.mydsl.pascal.PascalPackage#getrecordVariableList_Variable2()
   * @model containment="true"
   * @generated
   */
  EList<variable> getVariable2();

} // recordVariableList
