/**
 * generated by Xtext 2.16.0-SNAPSHOT
 */
package org.xtext.example.mydsl.pascal;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>String Start</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.pascal.StringStart#getStringStart <em>String Start</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.pascal.PascalPackage#getStringStart()
 * @model
 * @generated
 */
public interface StringStart extends EObject
{
  /**
   * Returns the value of the '<em><b>String Start</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>String Start</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>String Start</em>' attribute.
   * @see #setStringStart(String)
   * @see org.xtext.example.mydsl.pascal.PascalPackage#getStringStart_StringStart()
   * @model
   * @generated
   */
  String getStringStart();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.pascal.StringStart#getStringStart <em>String Start</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>String Start</em>' attribute.
   * @see #getStringStart()
   * @generated
   */
  void setStringStart(String value);

} // StringStart
