/**
 * generated by Xtext 2.16.0-SNAPSHOT
 */
package org.xtext.example.mydsl.pascal;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>type Start</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.pascal.typeStart#getTypeStart <em>Type Start</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.pascal.PascalPackage#gettypeStart()
 * @model
 * @generated
 */
public interface typeStart extends EObject
{
  /**
   * Returns the value of the '<em><b>Type Start</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Type Start</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type Start</em>' containment reference.
   * @see #setTypeStart(EObject)
   * @see org.xtext.example.mydsl.pascal.PascalPackage#gettypeStart_TypeStart()
   * @model containment="true"
   * @generated
   */
  EObject getTypeStart();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.pascal.typeStart#getTypeStart <em>Type Start</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Type Start</em>' containment reference.
   * @see #getTypeStart()
   * @generated
   */
  void setTypeStart(EObject value);

} // typeStart
