/**
 * generated by Xtext 2.16.0-SNAPSHOT
 */
package org.xtext.example.mydsl.pascal;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>unsigned Constant</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.pascal.unsignedConstant#getUnsignedNumber <em>Unsigned Number</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.pascal.unsignedConstant#getConstantChr <em>Constant Chr</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.pascal.unsignedConstant#getStringStart <em>String Start</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.pascal.unsignedConstant#getNil <em>Nil</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.pascal.PascalPackage#getunsignedConstant()
 * @model
 * @generated
 */
public interface unsignedConstant extends EObject
{
  /**
   * Returns the value of the '<em><b>Unsigned Number</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Unsigned Number</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Unsigned Number</em>' containment reference.
   * @see #setUnsignedNumber(unsignedNumber)
   * @see org.xtext.example.mydsl.pascal.PascalPackage#getunsignedConstant_UnsignedNumber()
   * @model containment="true"
   * @generated
   */
  unsignedNumber getUnsignedNumber();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.pascal.unsignedConstant#getUnsignedNumber <em>Unsigned Number</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Unsigned Number</em>' containment reference.
   * @see #getUnsignedNumber()
   * @generated
   */
  void setUnsignedNumber(unsignedNumber value);

  /**
   * Returns the value of the '<em><b>Constant Chr</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Constant Chr</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Constant Chr</em>' containment reference.
   * @see #setConstantChr(constantChr)
   * @see org.xtext.example.mydsl.pascal.PascalPackage#getunsignedConstant_ConstantChr()
   * @model containment="true"
   * @generated
   */
  constantChr getConstantChr();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.pascal.unsignedConstant#getConstantChr <em>Constant Chr</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Constant Chr</em>' containment reference.
   * @see #getConstantChr()
   * @generated
   */
  void setConstantChr(constantChr value);

  /**
   * Returns the value of the '<em><b>String Start</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>String Start</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>String Start</em>' containment reference.
   * @see #setStringStart(StringStart)
   * @see org.xtext.example.mydsl.pascal.PascalPackage#getunsignedConstant_StringStart()
   * @model containment="true"
   * @generated
   */
  StringStart getStringStart();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.pascal.unsignedConstant#getStringStart <em>String Start</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>String Start</em>' containment reference.
   * @see #getStringStart()
   * @generated
   */
  void setStringStart(StringStart value);

  /**
   * Returns the value of the '<em><b>Nil</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Nil</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Nil</em>' attribute.
   * @see #setNil(String)
   * @see org.xtext.example.mydsl.pascal.PascalPackage#getunsignedConstant_Nil()
   * @model
   * @generated
   */
  String getNil();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.pascal.unsignedConstant#getNil <em>Nil</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Nil</em>' attribute.
   * @see #getNil()
   * @generated
   */
  void setNil(String value);

} // unsignedConstant
