/**
 * generated by Xtext 2.15.0
 */
package org.xtext.example.mydsl.pascal.impl;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.example.mydsl.pascal.PascalPackage;
import org.xtext.example.mydsl.pascal.identifier;
import org.xtext.example.mydsl.pascal.tag;
import org.xtext.example.mydsl.pascal.typeIdentifier;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>tag</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.pascal.impl.tagImpl#getID <em>ID</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.pascal.impl.tagImpl#getTypeIdentifier1 <em>Type Identifier1</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.pascal.impl.tagImpl#getTypeIdentifier2 <em>Type Identifier2</em>}</li>
 * </ul>
 * </p>
 *
 * @generated
 */
public class tagImpl extends MinimalEObjectImpl.Container implements tag
{
  /**
   * The cached value of the '{@link #getID() <em>ID</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getID()
   * @generated
   * @ordered
   */
  protected identifier id;

  /**
   * The cached value of the '{@link #getTypeIdentifier1() <em>Type Identifier1</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTypeIdentifier1()
   * @generated
   * @ordered
   */
  protected typeIdentifier typeIdentifier1;

  /**
   * The cached value of the '{@link #getTypeIdentifier2() <em>Type Identifier2</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTypeIdentifier2()
   * @generated
   * @ordered
   */
  protected typeIdentifier typeIdentifier2;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected tagImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return PascalPackage.Literals.TAG;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public identifier getID()
  {
    return id;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetID(identifier newID, NotificationChain msgs)
  {
    identifier oldID = id;
    id = newID;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, PascalPackage.TAG__ID, oldID, newID);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setID(identifier newID)
  {
    if (newID != id)
    {
      NotificationChain msgs = null;
      if (id != null)
        msgs = ((InternalEObject)id).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - PascalPackage.TAG__ID, null, msgs);
      if (newID != null)
        msgs = ((InternalEObject)newID).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - PascalPackage.TAG__ID, null, msgs);
      msgs = basicSetID(newID, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, PascalPackage.TAG__ID, newID, newID));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public typeIdentifier getTypeIdentifier1()
  {
    return typeIdentifier1;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetTypeIdentifier1(typeIdentifier newTypeIdentifier1, NotificationChain msgs)
  {
    typeIdentifier oldTypeIdentifier1 = typeIdentifier1;
    typeIdentifier1 = newTypeIdentifier1;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, PascalPackage.TAG__TYPE_IDENTIFIER1, oldTypeIdentifier1, newTypeIdentifier1);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setTypeIdentifier1(typeIdentifier newTypeIdentifier1)
  {
    if (newTypeIdentifier1 != typeIdentifier1)
    {
      NotificationChain msgs = null;
      if (typeIdentifier1 != null)
        msgs = ((InternalEObject)typeIdentifier1).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - PascalPackage.TAG__TYPE_IDENTIFIER1, null, msgs);
      if (newTypeIdentifier1 != null)
        msgs = ((InternalEObject)newTypeIdentifier1).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - PascalPackage.TAG__TYPE_IDENTIFIER1, null, msgs);
      msgs = basicSetTypeIdentifier1(newTypeIdentifier1, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, PascalPackage.TAG__TYPE_IDENTIFIER1, newTypeIdentifier1, newTypeIdentifier1));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public typeIdentifier getTypeIdentifier2()
  {
    return typeIdentifier2;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetTypeIdentifier2(typeIdentifier newTypeIdentifier2, NotificationChain msgs)
  {
    typeIdentifier oldTypeIdentifier2 = typeIdentifier2;
    typeIdentifier2 = newTypeIdentifier2;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, PascalPackage.TAG__TYPE_IDENTIFIER2, oldTypeIdentifier2, newTypeIdentifier2);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setTypeIdentifier2(typeIdentifier newTypeIdentifier2)
  {
    if (newTypeIdentifier2 != typeIdentifier2)
    {
      NotificationChain msgs = null;
      if (typeIdentifier2 != null)
        msgs = ((InternalEObject)typeIdentifier2).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - PascalPackage.TAG__TYPE_IDENTIFIER2, null, msgs);
      if (newTypeIdentifier2 != null)
        msgs = ((InternalEObject)newTypeIdentifier2).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - PascalPackage.TAG__TYPE_IDENTIFIER2, null, msgs);
      msgs = basicSetTypeIdentifier2(newTypeIdentifier2, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, PascalPackage.TAG__TYPE_IDENTIFIER2, newTypeIdentifier2, newTypeIdentifier2));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case PascalPackage.TAG__ID:
        return basicSetID(null, msgs);
      case PascalPackage.TAG__TYPE_IDENTIFIER1:
        return basicSetTypeIdentifier1(null, msgs);
      case PascalPackage.TAG__TYPE_IDENTIFIER2:
        return basicSetTypeIdentifier2(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case PascalPackage.TAG__ID:
        return getID();
      case PascalPackage.TAG__TYPE_IDENTIFIER1:
        return getTypeIdentifier1();
      case PascalPackage.TAG__TYPE_IDENTIFIER2:
        return getTypeIdentifier2();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case PascalPackage.TAG__ID:
        setID((identifier)newValue);
        return;
      case PascalPackage.TAG__TYPE_IDENTIFIER1:
        setTypeIdentifier1((typeIdentifier)newValue);
        return;
      case PascalPackage.TAG__TYPE_IDENTIFIER2:
        setTypeIdentifier2((typeIdentifier)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case PascalPackage.TAG__ID:
        setID((identifier)null);
        return;
      case PascalPackage.TAG__TYPE_IDENTIFIER1:
        setTypeIdentifier1((typeIdentifier)null);
        return;
      case PascalPackage.TAG__TYPE_IDENTIFIER2:
        setTypeIdentifier2((typeIdentifier)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case PascalPackage.TAG__ID:
        return id != null;
      case PascalPackage.TAG__TYPE_IDENTIFIER1:
        return typeIdentifier1 != null;
      case PascalPackage.TAG__TYPE_IDENTIFIER2:
        return typeIdentifier2 != null;
    }
    return super.eIsSet(featureID);
  }

} //tagImpl
