/**
 * generated by Xtext 2.15.0
 */
package org.xtext.example.mydsl.pascal.impl;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.example.mydsl.pascal.PascalPackage;
import org.xtext.example.mydsl.pascal.recordVariableList;
import org.xtext.example.mydsl.pascal.statement;
import org.xtext.example.mydsl.pascal.withStatement;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>with Statement</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.pascal.impl.withStatementImpl#getRecordVariableList <em>Record Variable List</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.pascal.impl.withStatementImpl#getStatement <em>Statement</em>}</li>
 * </ul>
 * </p>
 *
 * @generated
 */
public class withStatementImpl extends MinimalEObjectImpl.Container implements withStatement
{
  /**
   * The cached value of the '{@link #getRecordVariableList() <em>Record Variable List</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getRecordVariableList()
   * @generated
   * @ordered
   */
  protected recordVariableList recordVariableList;

  /**
   * The cached value of the '{@link #getStatement() <em>Statement</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getStatement()
   * @generated
   * @ordered
   */
  protected statement statement;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected withStatementImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return PascalPackage.Literals.WITH_STATEMENT;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public recordVariableList getRecordVariableList()
  {
    return recordVariableList;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetRecordVariableList(recordVariableList newRecordVariableList, NotificationChain msgs)
  {
    recordVariableList oldRecordVariableList = recordVariableList;
    recordVariableList = newRecordVariableList;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, PascalPackage.WITH_STATEMENT__RECORD_VARIABLE_LIST, oldRecordVariableList, newRecordVariableList);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setRecordVariableList(recordVariableList newRecordVariableList)
  {
    if (newRecordVariableList != recordVariableList)
    {
      NotificationChain msgs = null;
      if (recordVariableList != null)
        msgs = ((InternalEObject)recordVariableList).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - PascalPackage.WITH_STATEMENT__RECORD_VARIABLE_LIST, null, msgs);
      if (newRecordVariableList != null)
        msgs = ((InternalEObject)newRecordVariableList).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - PascalPackage.WITH_STATEMENT__RECORD_VARIABLE_LIST, null, msgs);
      msgs = basicSetRecordVariableList(newRecordVariableList, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, PascalPackage.WITH_STATEMENT__RECORD_VARIABLE_LIST, newRecordVariableList, newRecordVariableList));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public statement getStatement()
  {
    return statement;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetStatement(statement newStatement, NotificationChain msgs)
  {
    statement oldStatement = statement;
    statement = newStatement;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, PascalPackage.WITH_STATEMENT__STATEMENT, oldStatement, newStatement);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setStatement(statement newStatement)
  {
    if (newStatement != statement)
    {
      NotificationChain msgs = null;
      if (statement != null)
        msgs = ((InternalEObject)statement).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - PascalPackage.WITH_STATEMENT__STATEMENT, null, msgs);
      if (newStatement != null)
        msgs = ((InternalEObject)newStatement).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - PascalPackage.WITH_STATEMENT__STATEMENT, null, msgs);
      msgs = basicSetStatement(newStatement, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, PascalPackage.WITH_STATEMENT__STATEMENT, newStatement, newStatement));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case PascalPackage.WITH_STATEMENT__RECORD_VARIABLE_LIST:
        return basicSetRecordVariableList(null, msgs);
      case PascalPackage.WITH_STATEMENT__STATEMENT:
        return basicSetStatement(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case PascalPackage.WITH_STATEMENT__RECORD_VARIABLE_LIST:
        return getRecordVariableList();
      case PascalPackage.WITH_STATEMENT__STATEMENT:
        return getStatement();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case PascalPackage.WITH_STATEMENT__RECORD_VARIABLE_LIST:
        setRecordVariableList((recordVariableList)newValue);
        return;
      case PascalPackage.WITH_STATEMENT__STATEMENT:
        setStatement((statement)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case PascalPackage.WITH_STATEMENT__RECORD_VARIABLE_LIST:
        setRecordVariableList((recordVariableList)null);
        return;
      case PascalPackage.WITH_STATEMENT__STATEMENT:
        setStatement((statement)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case PascalPackage.WITH_STATEMENT__RECORD_VARIABLE_LIST:
        return recordVariableList != null;
      case PascalPackage.WITH_STATEMENT__STATEMENT:
        return statement != null;
    }
    return super.eIsSet(featureID);
  }

} //withStatementImpl
