/**
 * generated by Xtext 2.16.0-SNAPSHOT
 */
package org.xtext.example.mydsl.pascal.impl;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.example.mydsl.pascal.PascalPackage;
import org.xtext.example.mydsl.pascal.fixedPart;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>fixed Part</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class fixedPartImpl extends MinimalEObjectImpl.Container implements fixedPart
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected fixedPartImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return PascalPackage.Literals.FIXED_PART;
  }

} //fixedPartImpl
