/**
 * generated by Xtext 2.16.0-SNAPSHOT
 */
package org.xtext.example.mydsl.pascal.impl;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.example.mydsl.pascal.PascalPackage;
import org.xtext.example.mydsl.pascal.labelStart;
import org.xtext.example.mydsl.pascal.statement;
import org.xtext.example.mydsl.pascal.unlabelledStatement;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>statement</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.pascal.impl.statementImpl#getLabelStart <em>Label Start</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.pascal.impl.statementImpl#getUnlabelledStatement <em>Unlabelled Statement</em>}</li>
 * </ul>
 *
 * @generated
 */
public class statementImpl extends MinimalEObjectImpl.Container implements statement
{
  /**
   * The cached value of the '{@link #getLabelStart() <em>Label Start</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getLabelStart()
   * @generated
   * @ordered
   */
  protected labelStart labelStart;

  /**
   * The cached value of the '{@link #getUnlabelledStatement() <em>Unlabelled Statement</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getUnlabelledStatement()
   * @generated
   * @ordered
   */
  protected unlabelledStatement unlabelledStatement;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected statementImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return PascalPackage.Literals.STATEMENT;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public labelStart getLabelStart()
  {
    return labelStart;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetLabelStart(labelStart newLabelStart, NotificationChain msgs)
  {
    labelStart oldLabelStart = labelStart;
    labelStart = newLabelStart;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, PascalPackage.STATEMENT__LABEL_START, oldLabelStart, newLabelStart);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setLabelStart(labelStart newLabelStart)
  {
    if (newLabelStart != labelStart)
    {
      NotificationChain msgs = null;
      if (labelStart != null)
        msgs = ((InternalEObject)labelStart).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - PascalPackage.STATEMENT__LABEL_START, null, msgs);
      if (newLabelStart != null)
        msgs = ((InternalEObject)newLabelStart).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - PascalPackage.STATEMENT__LABEL_START, null, msgs);
      msgs = basicSetLabelStart(newLabelStart, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, PascalPackage.STATEMENT__LABEL_START, newLabelStart, newLabelStart));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public unlabelledStatement getUnlabelledStatement()
  {
    return unlabelledStatement;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetUnlabelledStatement(unlabelledStatement newUnlabelledStatement, NotificationChain msgs)
  {
    unlabelledStatement oldUnlabelledStatement = unlabelledStatement;
    unlabelledStatement = newUnlabelledStatement;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, PascalPackage.STATEMENT__UNLABELLED_STATEMENT, oldUnlabelledStatement, newUnlabelledStatement);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setUnlabelledStatement(unlabelledStatement newUnlabelledStatement)
  {
    if (newUnlabelledStatement != unlabelledStatement)
    {
      NotificationChain msgs = null;
      if (unlabelledStatement != null)
        msgs = ((InternalEObject)unlabelledStatement).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - PascalPackage.STATEMENT__UNLABELLED_STATEMENT, null, msgs);
      if (newUnlabelledStatement != null)
        msgs = ((InternalEObject)newUnlabelledStatement).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - PascalPackage.STATEMENT__UNLABELLED_STATEMENT, null, msgs);
      msgs = basicSetUnlabelledStatement(newUnlabelledStatement, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, PascalPackage.STATEMENT__UNLABELLED_STATEMENT, newUnlabelledStatement, newUnlabelledStatement));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case PascalPackage.STATEMENT__LABEL_START:
        return basicSetLabelStart(null, msgs);
      case PascalPackage.STATEMENT__UNLABELLED_STATEMENT:
        return basicSetUnlabelledStatement(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case PascalPackage.STATEMENT__LABEL_START:
        return getLabelStart();
      case PascalPackage.STATEMENT__UNLABELLED_STATEMENT:
        return getUnlabelledStatement();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case PascalPackage.STATEMENT__LABEL_START:
        setLabelStart((labelStart)newValue);
        return;
      case PascalPackage.STATEMENT__UNLABELLED_STATEMENT:
        setUnlabelledStatement((unlabelledStatement)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case PascalPackage.STATEMENT__LABEL_START:
        setLabelStart((labelStart)null);
        return;
      case PascalPackage.STATEMENT__UNLABELLED_STATEMENT:
        setUnlabelledStatement((unlabelledStatement)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case PascalPackage.STATEMENT__LABEL_START:
        return labelStart != null;
      case PascalPackage.STATEMENT__UNLABELLED_STATEMENT:
        return unlabelledStatement != null;
    }
    return super.eIsSet(featureID);
  }

} //statementImpl
