/**
 * generated by Xtext 2.16.0-SNAPSHOT
 */
package org.xtext.example.mydsl.pascal.impl;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.example.mydsl.pascal.PascalPackage;
import org.xtext.example.mydsl.pascal.identifier;
import org.xtext.example.mydsl.pascal.stringtype;
import org.xtext.example.mydsl.pascal.unsignedNumber;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>stringtype</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.pascal.impl.stringtypeImpl#getStringTerminal <em>String Terminal</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.pascal.impl.stringtypeImpl#getID <em>ID</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.pascal.impl.stringtypeImpl#getUnsignedNumber <em>Unsigned Number</em>}</li>
 * </ul>
 *
 * @generated
 */
public class stringtypeImpl extends MinimalEObjectImpl.Container implements stringtype
{
  /**
   * The default value of the '{@link #getStringTerminal() <em>String Terminal</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getStringTerminal()
   * @generated
   * @ordered
   */
  protected static final String STRING_TERMINAL_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getStringTerminal() <em>String Terminal</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getStringTerminal()
   * @generated
   * @ordered
   */
  protected String stringTerminal = STRING_TERMINAL_EDEFAULT;

  /**
   * The cached value of the '{@link #getID() <em>ID</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getID()
   * @generated
   * @ordered
   */
  protected identifier id;

  /**
   * The cached value of the '{@link #getUnsignedNumber() <em>Unsigned Number</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getUnsignedNumber()
   * @generated
   * @ordered
   */
  protected unsignedNumber unsignedNumber;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected stringtypeImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return PascalPackage.Literals.STRINGTYPE;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getStringTerminal()
  {
    return stringTerminal;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setStringTerminal(String newStringTerminal)
  {
    String oldStringTerminal = stringTerminal;
    stringTerminal = newStringTerminal;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, PascalPackage.STRINGTYPE__STRING_TERMINAL, oldStringTerminal, stringTerminal));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public identifier getID()
  {
    return id;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetID(identifier newID, NotificationChain msgs)
  {
    identifier oldID = id;
    id = newID;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, PascalPackage.STRINGTYPE__ID, oldID, newID);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setID(identifier newID)
  {
    if (newID != id)
    {
      NotificationChain msgs = null;
      if (id != null)
        msgs = ((InternalEObject)id).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - PascalPackage.STRINGTYPE__ID, null, msgs);
      if (newID != null)
        msgs = ((InternalEObject)newID).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - PascalPackage.STRINGTYPE__ID, null, msgs);
      msgs = basicSetID(newID, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, PascalPackage.STRINGTYPE__ID, newID, newID));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public unsignedNumber getUnsignedNumber()
  {
    return unsignedNumber;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetUnsignedNumber(unsignedNumber newUnsignedNumber, NotificationChain msgs)
  {
    unsignedNumber oldUnsignedNumber = unsignedNumber;
    unsignedNumber = newUnsignedNumber;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, PascalPackage.STRINGTYPE__UNSIGNED_NUMBER, oldUnsignedNumber, newUnsignedNumber);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setUnsignedNumber(unsignedNumber newUnsignedNumber)
  {
    if (newUnsignedNumber != unsignedNumber)
    {
      NotificationChain msgs = null;
      if (unsignedNumber != null)
        msgs = ((InternalEObject)unsignedNumber).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - PascalPackage.STRINGTYPE__UNSIGNED_NUMBER, null, msgs);
      if (newUnsignedNumber != null)
        msgs = ((InternalEObject)newUnsignedNumber).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - PascalPackage.STRINGTYPE__UNSIGNED_NUMBER, null, msgs);
      msgs = basicSetUnsignedNumber(newUnsignedNumber, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, PascalPackage.STRINGTYPE__UNSIGNED_NUMBER, newUnsignedNumber, newUnsignedNumber));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case PascalPackage.STRINGTYPE__ID:
        return basicSetID(null, msgs);
      case PascalPackage.STRINGTYPE__UNSIGNED_NUMBER:
        return basicSetUnsignedNumber(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case PascalPackage.STRINGTYPE__STRING_TERMINAL:
        return getStringTerminal();
      case PascalPackage.STRINGTYPE__ID:
        return getID();
      case PascalPackage.STRINGTYPE__UNSIGNED_NUMBER:
        return getUnsignedNumber();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case PascalPackage.STRINGTYPE__STRING_TERMINAL:
        setStringTerminal((String)newValue);
        return;
      case PascalPackage.STRINGTYPE__ID:
        setID((identifier)newValue);
        return;
      case PascalPackage.STRINGTYPE__UNSIGNED_NUMBER:
        setUnsignedNumber((unsignedNumber)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case PascalPackage.STRINGTYPE__STRING_TERMINAL:
        setStringTerminal(STRING_TERMINAL_EDEFAULT);
        return;
      case PascalPackage.STRINGTYPE__ID:
        setID((identifier)null);
        return;
      case PascalPackage.STRINGTYPE__UNSIGNED_NUMBER:
        setUnsignedNumber((unsignedNumber)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case PascalPackage.STRINGTYPE__STRING_TERMINAL:
        return STRING_TERMINAL_EDEFAULT == null ? stringTerminal != null : !STRING_TERMINAL_EDEFAULT.equals(stringTerminal);
      case PascalPackage.STRINGTYPE__ID:
        return id != null;
      case PascalPackage.STRINGTYPE__UNSIGNED_NUMBER:
        return unsignedNumber != null;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (stringTerminal: ");
    result.append(stringTerminal);
    result.append(')');
    return result.toString();
  }

} //stringtypeImpl
