/**
 * generated by Xtext 2.16.0-SNAPSHOT
 */
package org.xtext.example.mydsl.pascal.impl;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.example.mydsl.pascal.PascalPackage;
import org.xtext.example.mydsl.pascal.structuredType;
import org.xtext.example.mydsl.pascal.unpackedStructuredType;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>structured Type</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.pascal.impl.structuredTypeImpl#getUnpackedStructuredType1 <em>Unpacked Structured Type1</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.pascal.impl.structuredTypeImpl#getUnpackedStructuredType2 <em>Unpacked Structured Type2</em>}</li>
 * </ul>
 *
 * @generated
 */
public class structuredTypeImpl extends MinimalEObjectImpl.Container implements structuredType
{
  /**
   * The cached value of the '{@link #getUnpackedStructuredType1() <em>Unpacked Structured Type1</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getUnpackedStructuredType1()
   * @generated
   * @ordered
   */
  protected unpackedStructuredType unpackedStructuredType1;

  /**
   * The cached value of the '{@link #getUnpackedStructuredType2() <em>Unpacked Structured Type2</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getUnpackedStructuredType2()
   * @generated
   * @ordered
   */
  protected unpackedStructuredType unpackedStructuredType2;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected structuredTypeImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return PascalPackage.Literals.STRUCTURED_TYPE;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public unpackedStructuredType getUnpackedStructuredType1()
  {
    return unpackedStructuredType1;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetUnpackedStructuredType1(unpackedStructuredType newUnpackedStructuredType1, NotificationChain msgs)
  {
    unpackedStructuredType oldUnpackedStructuredType1 = unpackedStructuredType1;
    unpackedStructuredType1 = newUnpackedStructuredType1;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, PascalPackage.STRUCTURED_TYPE__UNPACKED_STRUCTURED_TYPE1, oldUnpackedStructuredType1, newUnpackedStructuredType1);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setUnpackedStructuredType1(unpackedStructuredType newUnpackedStructuredType1)
  {
    if (newUnpackedStructuredType1 != unpackedStructuredType1)
    {
      NotificationChain msgs = null;
      if (unpackedStructuredType1 != null)
        msgs = ((InternalEObject)unpackedStructuredType1).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - PascalPackage.STRUCTURED_TYPE__UNPACKED_STRUCTURED_TYPE1, null, msgs);
      if (newUnpackedStructuredType1 != null)
        msgs = ((InternalEObject)newUnpackedStructuredType1).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - PascalPackage.STRUCTURED_TYPE__UNPACKED_STRUCTURED_TYPE1, null, msgs);
      msgs = basicSetUnpackedStructuredType1(newUnpackedStructuredType1, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, PascalPackage.STRUCTURED_TYPE__UNPACKED_STRUCTURED_TYPE1, newUnpackedStructuredType1, newUnpackedStructuredType1));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public unpackedStructuredType getUnpackedStructuredType2()
  {
    return unpackedStructuredType2;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetUnpackedStructuredType2(unpackedStructuredType newUnpackedStructuredType2, NotificationChain msgs)
  {
    unpackedStructuredType oldUnpackedStructuredType2 = unpackedStructuredType2;
    unpackedStructuredType2 = newUnpackedStructuredType2;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, PascalPackage.STRUCTURED_TYPE__UNPACKED_STRUCTURED_TYPE2, oldUnpackedStructuredType2, newUnpackedStructuredType2);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setUnpackedStructuredType2(unpackedStructuredType newUnpackedStructuredType2)
  {
    if (newUnpackedStructuredType2 != unpackedStructuredType2)
    {
      NotificationChain msgs = null;
      if (unpackedStructuredType2 != null)
        msgs = ((InternalEObject)unpackedStructuredType2).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - PascalPackage.STRUCTURED_TYPE__UNPACKED_STRUCTURED_TYPE2, null, msgs);
      if (newUnpackedStructuredType2 != null)
        msgs = ((InternalEObject)newUnpackedStructuredType2).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - PascalPackage.STRUCTURED_TYPE__UNPACKED_STRUCTURED_TYPE2, null, msgs);
      msgs = basicSetUnpackedStructuredType2(newUnpackedStructuredType2, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, PascalPackage.STRUCTURED_TYPE__UNPACKED_STRUCTURED_TYPE2, newUnpackedStructuredType2, newUnpackedStructuredType2));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case PascalPackage.STRUCTURED_TYPE__UNPACKED_STRUCTURED_TYPE1:
        return basicSetUnpackedStructuredType1(null, msgs);
      case PascalPackage.STRUCTURED_TYPE__UNPACKED_STRUCTURED_TYPE2:
        return basicSetUnpackedStructuredType2(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case PascalPackage.STRUCTURED_TYPE__UNPACKED_STRUCTURED_TYPE1:
        return getUnpackedStructuredType1();
      case PascalPackage.STRUCTURED_TYPE__UNPACKED_STRUCTURED_TYPE2:
        return getUnpackedStructuredType2();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case PascalPackage.STRUCTURED_TYPE__UNPACKED_STRUCTURED_TYPE1:
        setUnpackedStructuredType1((unpackedStructuredType)newValue);
        return;
      case PascalPackage.STRUCTURED_TYPE__UNPACKED_STRUCTURED_TYPE2:
        setUnpackedStructuredType2((unpackedStructuredType)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case PascalPackage.STRUCTURED_TYPE__UNPACKED_STRUCTURED_TYPE1:
        setUnpackedStructuredType1((unpackedStructuredType)null);
        return;
      case PascalPackage.STRUCTURED_TYPE__UNPACKED_STRUCTURED_TYPE2:
        setUnpackedStructuredType2((unpackedStructuredType)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case PascalPackage.STRUCTURED_TYPE__UNPACKED_STRUCTURED_TYPE1:
        return unpackedStructuredType1 != null;
      case PascalPackage.STRUCTURED_TYPE__UNPACKED_STRUCTURED_TYPE2:
        return unpackedStructuredType2 != null;
    }
    return super.eIsSet(featureID);
  }

} //structuredTypeImpl
